import React from 'react';
import { useParams } from 'react-router';
import { useStrategicFramingWorkspace } from './useStrategicFramingWorkspace';
import { useStrategicFramingLensSuggestions } from './useStrategicFramingLensSuggestions';
import { LensSuggestions } from './StrategicFramingLensSuggestions';
import { promoteStrategicFramingChallenge, reviewStrategicFramingChallengeStructure, reviewStrategicFramingPrioritization } from './service';
import { listStrategicFronts } from '../../../app/services/portfolioService';
import type { StrategicFramingDraft, SubjectLevel } from './types';

const subjectLabels: Record<SubjectLevel, string> = { front_like: 'Frente estratégico posible', challenge_like: 'Reto o problema específico', initiative_like: 'Iniciativa o intervención', unresolved: 'Aún por definir' };
const parentLabels = { known: 'Contexto estratégico identificado', provisional: 'Relación estratégica por validar', unresolved: 'Contexto estratégico aún no resuelto' };
const sourceLabels: Record<string, string> = { public_entry: 'Entrada pública', enterprise_direct: 'Entrada corporativa', existing_portfolio: 'Portafolio existente' };

export function StrategicFramingWorkspacePage() {
  const { stateId = '' } = useParams();
  const workspace = useStrategicFramingWorkspace(stateId);
  const lenses = useStrategicFramingLensSuggestions(stateId, workspace.serverState?.version ?? null);
  if (workspace.status === 'loading') return <StateMessage text="Cargando el framing provisional…" />;
  if (workspace.status === 'error' && !workspace.serverState) return <StateMessage text={workspace.error?.code === 'SF_PROVISIONAL_STATE_NOT_FOUND' ? 'No encontramos este framing provisional.' : workspace.error?.code === 'SF_PROVISIONAL_STATE_FORBIDDEN' ? 'No tienes acceso a este framing.' : 'No pudimos cargar este framing.'} action={workspace.reload} />;
  if (!workspace.serverState || !workspace.draft) return null;
  const { serverState: state, draft } = workspace;
  const field = (key: keyof StrategicFramingDraft) => (value: string) => workspace.update(key, value || null);
  const applyDisposition = async (candidateId: string, disposition: 'address_now' | 'observe' | 'discard') => {
    const recommendation = workspace.recommendations?.recommendations.find(item => item.candidateId === candidateId);
    if (!recommendation) return;
    try { await reviewStrategicFramingPrioritization(stateId, { expectedVersion: state.version, decisions: [{ candidateId, disposition, recommendationSnapshot: recommendation.recommendationSnapshot }] }); await workspace.reload(); } catch { await workspace.reload(); }
  };
  const saveGroup = async (candidateId: string, statement: string) => {
    try { await reviewStrategicFramingChallengeStructure(stateId, { expectedVersion: state.version, groups: [{ ...(candidateId === 'new' ? {} : { challengeCandidateId: candidateId }), sourceCandidateIds: state.prioritizationState.candidates.filter(c => c.humanDisposition === 'address_now').map(c => c.candidateId), relatedWorkRefs: [], statement, structureKind: 'one_challenge', structuralRecommendationRef: null, structuralRecommendationVersion: null }] }); await workspace.reload(); } catch { await workspace.reload(); }
  };
  return <main className="mx-auto max-w-7xl space-y-6 p-6 md:p-10">
    <div className="text-sm text-slate-500"><a href="/portfolio/inicio" className="hover:text-slate-900">Portfolio Lead</a> <span className="mx-2">/</span> Strategic Framing</div>
    <header className="flex flex-wrap items-start justify-between gap-4">
      <div><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-700">Strategic Framing</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">{draft.intendedMovement || 'Define qué quieres mover'}</h1><p className="mt-2 max-w-2xl text-slate-600">Estado provisional. Revisa y ajusta cómo estamos entendiendo este contexto antes de convertirlo en estructura estratégica formal.</p></div>
      <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Provisional</strong><div className="mt-1 text-xs">Versión {state.version} · {sourceLabels[state.sourceMode] ?? 'Origen no especificado'}</div></div>
    </header>
    {workspace.conflict && <div role="alert" className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-900">Este framing fue actualizado en otra sesión. Recarga la versión más reciente antes de guardar tus cambios.<button className="rounded-xl bg-white px-3 py-2 font-semibold" onClick={workspace.reload}>Recargar versión</button></div>}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">
      <section className="space-y-6">
        <Card title="Qué quieres mover"><TextArea label="Movimiento intencionado" value={draft.intendedMovement} onChange={field('intendedMovement')} /><TextArea label="Por qué importa" value={draft.whyItMatters} onChange={field('whyItMatters')} /></Card>
        <Card title="Cómo lo estamos interpretando"><label className="block text-sm font-semibold text-slate-700">Clasificación actual<select className="mt-2 w-full rounded-xl border border-slate-200 p-3" value={draft.subjectLevel} onChange={e => workspace.update('subjectLevel', e.target.value as SubjectLevel)}>{Object.entries(subjectLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><strong>Interpretación inicial de Starteria</strong><p className="mt-2">Confianza: {state.scopeAssessment.confidence}</p>{state.scopeAssessment.rationale.map(item => <p key={item} className="mt-1">{item}</p>)}</div></Card>
        <Card title="Cómo sabremos que se mueve"><div className="grid gap-4 md:grid-cols-2"><Select label="Estado de la señal" value={draft.movementSignalStatus ?? ''} options={['confirmed', 'proxy', 'suggested', 'unknown', 'conflicting']} onChange={value => workspace.update('movementSignalStatus', (value || null) as StrategicFramingDraft['movementSignalStatus'])} /><TextInput label="Señal o valor proxy" value={draft.movementSignalValue} onChange={field('movementSignalValue')} /></div><TextArea label="Horizonte" value={draft.horizonContext} onChange={field('horizonContext')} /><TextArea label="Decisión que habilita" value={draft.decisionToEnable} onChange={field('decisionToEnable')} /></Card>
        <Card title="Relación estratégica"><Select label="Estado del contexto" value={draft.parentStatus} options={Object.keys(parentLabels)} optionLabels={parentLabels} onChange={value => workspace.update('parentStatus', value as StrategicFramingDraft['parentStatus'])} /><TextInput label="Descripción humana del contexto" value={draft.parentLabel} onChange={field('parentLabel')} /></Card>
        <PrioritizationSection state={state} recommendations={workspace.recommendations} onDisposition={applyDisposition} />
        <StructuringSection state={state} onSave={saveGroup} promotions={workspace.promotions} />
        <PromotionSection state={state} promotions={workspace.promotions} onReload={workspace.reload} />
      </section>
      <aside className="space-y-6"><LensSuggestions stateDirty={workspace.dirty} lenses={lenses} /><Card title="Qué falta para avanzar"><p className="text-xs uppercase tracking-wide text-slate-500">Evaluación actual · {state.sufficiency.status}</p><Gap title="Bloqueos" items={state.sufficiency.blockers} /><Gap title="Brechas suaves" items={state.sufficiency.softGaps} /><Gap title="Contexto opcional" items={state.sufficiency.optionalContext} /></Card><Card title="Contexto"><p className="text-sm text-slate-600">Última actualización</p><p className="mt-1 text-sm font-semibold text-slate-900">{new Date(state.updatedAt).toLocaleString('es-ES')}</p><p className="mt-4 text-sm text-slate-600">La procedencia y la evaluación son de solo lectura en esta versión.</p></Card></aside>
    </div>
    <footer className="flex justify-end gap-3 border-t border-slate-200 pt-5"><button className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700" onClick={workspace.cancel} disabled={!workspace.dirty}>Cancelar cambios</button><button className="rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40" onClick={workspace.save} disabled={!workspace.dirty || workspace.status === 'saving'}>{workspace.status === 'saving' ? 'Guardando…' : 'Guardar cambios'}</button></footer>
  </main>;
}

function PrioritizationSection({ state, recommendations, onDisposition }: { state: any; recommendations: any; onDisposition: (id: string, disposition: 'address_now' | 'observe' | 'discard') => void }) {
  const candidates = state.prioritizationState?.candidates ?? [];
  return <Card title="Priorización humana"><p className="mb-4 text-sm text-slate-600">Startería recomienda; tú decides. Capacidad actual: {state.prioritizationState?.focusSlots == null ? 'no definida' : state.prioritizationState.focusSlots}</p>{candidates.length === 0 ? <p className="text-sm text-slate-500">No hay gaps u oportunidades para revisar.</p> : candidates.map((candidate: any) => { const rec = recommendations?.recommendations.find((item: any) => item.candidateId === candidate.candidateId); return <div key={candidate.candidateId} className="border-t border-slate-100 py-4"><div className="text-xs font-semibold uppercase text-slate-500">{candidate.kind}</div><p className="mt-1 font-semibold text-slate-900">{candidate.statementSnapshot}</p><p className="mt-2 text-sm text-slate-600"><strong>Startería recomienda:</strong> {rec?.recommendedDisposition ?? 'sin recomendación'}</p><p className="text-sm text-slate-600"><strong>Tu decisión:</strong> {candidate.humanDisposition}</p><div className="mt-3 flex gap-2">{(['address_now', 'observe', 'discard'] as const).map(disposition => <button key={disposition} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold" onClick={() => onDisposition(candidate.candidateId, disposition)}>{disposition}</button>)}</div></div>; })}</Card>;
}

function StructuringSection({ state, onSave, promotions }: { state: any; onSave: (id: string, statement: string) => void; promotions: Array<{ challengeCandidateId: string }> }) {
  const eligible = (state.prioritizationState?.candidates ?? []).filter((candidate: any) => candidate.humanDisposition === 'address_now');
  const groups = state.challengeStructuringState?.candidates ?? [];
  const [keptProvisional, setKeptProvisional] = React.useState(false);
  return <Card title="Estructura de ChallengeCandidates"><p className="mb-4 text-sm text-slate-600">Solo ADDRESS NOW puede entrar en una estructura provisional. Confirmar aquí no crea un Challenge canónico.</p>{eligible.length === 0 ? <p className="text-sm text-slate-500">Marca al menos un elemento como address_now para estructurar.</p> : <div className="space-y-3">{groups.length ? groups.map((group: any) => <div key={group.challengeCandidateId} className="rounded-xl bg-slate-50 p-3"><label className="block text-sm font-semibold">Declaración del ChallengeCandidate<textarea className="mt-2 w-full rounded-lg border border-slate-200 p-2 font-normal" defaultValue={group.statement} onBlur={event => onSave(group.challengeCandidateId, event.currentTarget.value)} /></label>{group.structuralRecommendationRef && <p className="mt-2 text-xs text-slate-500">Recomendación estructural advisory: {group.structuralRecommendationRef} {group.structuralRecommendationVersion ?? ''}</p>}<p className="mt-2 text-xs text-slate-500">{promotions.some(item => item.challengeCandidateId === group.challengeCandidateId) ? 'Promovido' : 'Confirmado / listo para revisión'}</p></div>) : <div className="flex flex-wrap gap-2"><button className="rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white" onClick={() => onSave('new', 'Describe el ChallengeCandidate')}>Aceptar estructura propuesta</button><button className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold" onClick={() => setKeptProvisional(true)}>Mantener provisional</button>{keptProvisional && <p className="basis-full text-sm text-slate-600">Se mantiene provisional: no se crea ChallengeCandidate ni Challenge canónico.</p>}</div>}</div>}</Card>;
}

function PromotionSection({ state, promotions, onReload }: { state: any; promotions: Array<{ challengeCandidateId: string }>; onReload: () => void }) {
  const candidates = state.challengeStructuringState?.candidates ?? [];
  return <Card title="Promoción humana"><p className="mb-4 text-sm text-slate-600">La promoción requiere un ChallengeCandidate confirmado y la selección explícita de un Strategic Front canónico.</p>{candidates.length === 0 ? <p className="text-sm text-slate-500">Confirma primero una estructura.</p> : candidates.map((candidate: any) => <PromotionCandidate key={candidate.challengeCandidateId} state={state} candidate={candidate} promoted={promotions.some(item => item.challengeCandidateId === candidate.challengeCandidateId)} onReload={onReload} />)}</Card>;
}

function PromotionCandidate({ state, candidate, promoted, onReload }: { state: any; candidate: any; promoted: boolean; onReload: () => void }) {
  const [fronts, setFronts] = React.useState<Array<{ id: string; name: string }>>([]); const [frontError, setFrontError] = React.useState(''); const [frontId, setFrontId] = React.useState(''); const [title, setTitle] = React.useState(candidate.statement); const [type, setType] = React.useState<'correccion' | 'crecimiento' | 'exploracion'>('crecimiento'); const [confirmed, setConfirmed] = React.useState(false); const [error, setError] = React.useState(''); const [result, setResult] = React.useState<{ challengeId: string; promotionId: string; title: string; frontName: string } | null>(null);
  React.useEffect(() => { if (promoted) return; void listStrategicFronts().then(items => setFronts(items.map(item => ({ id: item.id, name: item.name })))).catch(() => setFrontError('No pudimos cargar los Frentes Estratégicos. Inténtalo de nuevo en esta sección.')); }, [promoted]);
  if (result) return <div role="status" className="border-t border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><strong>Challenge creado</strong><p>Título: {result.title}</p><p>Estado: Draft</p><p>Frente: {result.frontName}</p><p>Origen: Strategic Framing</p><p>Iniciativas creadas: 0</p><p className="mt-2 text-xs">challengeId: {result.challengeId} · promotionId: {result.promotionId} · challengeCandidateId: {candidate.challengeCandidateId}</p><a className="mt-2 inline-block font-semibold underline" href={`/retos/${result.challengeId}`}>Ver Challenge</a></div>;
  if (promoted) return <div className="border-t border-slate-100 py-3 text-sm"><strong>Promovido:</strong> {candidate.statement}</div>;
  const submit = async () => { if (!frontId) { setError(fronts.length ? 'Selecciona un Strategic Front canónico antes de promover.' : 'Antes de convertir este candidato en Challenge necesitamos resolver su relación con un Frente Estratégico.'); return; } if (!confirmed) { setError('Confirma explícitamente Front, título, declaración y tipo.'); return; } try { const response = await promoteStrategicFramingChallenge(state.id, { challengeCandidateId: candidate.challengeCandidateId, expectedVersion: state.version, strategicFrontId: frontId, title, statement: candidate.statement, type }); const frontName = fronts.find(front => front.id === frontId)?.name ?? frontId; setResult({ challengeId: response.challengeId, promotionId: response.promotionId, title: response.challengeTitle, frontName }); } catch (nextError: any) { setError(nextError?.message ?? 'No se pudo promover.'); } };
  return <div className="border-t border-slate-100 py-4"><p className="font-semibold">{candidate.statement}</p>{frontError && <p role="alert" className="mt-2 text-sm text-rose-700">{frontError}</p>}{!frontError && <><label className="mt-3 block text-sm font-semibold">Frente estratégico<select aria-label="Frente estratégico" className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" value={frontId} onChange={event => setFrontId(event.target.value)}><option value="">{fronts.length ? 'Selecciona un frente' : 'No hay frentes disponibles'}</option>{fronts.map(front => <option key={front.id} value={front.id}>{front.name}</option>)}</select></label>{!fronts.length && <p className="mt-2 text-sm text-amber-800">Antes de convertir este candidato en Challenge necesitamos resolver su relación con un Frente Estratégico.</p>}</>}<TextInput label="Título confirmado" value={title} onChange={setTitle} /><Select label="Tipo" value={type} options={['correccion', 'crecimiento', 'exploracion']} onChange={value => setType(value as typeof type)} /><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={event => setConfirmed(event.target.checked)} />Confirmo Front, título, declaración y tipo.</label>{error && <p role="alert" className="mt-2 text-sm text-rose-700">{error}</p>}<button className="mt-3 rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" disabled={!fronts.length || Boolean(frontError)} onClick={submit}>Promover Challenge</button></div>;
}

function Card({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-lg font-bold text-slate-950">{title}</h2>{children}</section>; }
function TextInput({ label, value, onChange }: { label: string; value: string | null; onChange: (value: string) => void }) { return <label className="mt-4 block text-sm font-semibold text-slate-700">{label}<input className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" value={value ?? ''} onChange={e => onChange(e.target.value)} /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string | null; onChange: (value: string) => void }) { return <label className="mt-4 block text-sm font-semibold text-slate-700">{label}<textarea className="mt-2 min-h-24 w-full rounded-xl border border-slate-200 p-3 font-normal" value={value ?? ''} onChange={e => onChange(e.target.value)} /></label>; }
function Select({ label, value, options, optionLabels, onChange }: { label: string; value: string; options: string[]; optionLabels?: Record<string, string>; onChange: (value: string) => void }) { return <label className="block text-sm font-semibold text-slate-700">{label}<select className="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal" value={value} onChange={e => onChange(e.target.value)}><option value="">Selecciona una opción</option>{options.map(option => <option key={option} value={option}>{optionLabels?.[option] ?? option}</option>)}</select></label>; }
function Gap({ title, items }: { title: string; items: string[] }) { return <div className="mt-4"><h3 className="text-sm font-semibold text-slate-800">{title}</h3>{items.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-600">{items.map(item => <li key={item}>{item}</li>)}</ul> : <p className="mt-1 text-sm text-slate-500">Ninguno registrado.</p>}</div>; }
function StateMessage({ text, action }: { text: string; action?: () => void }) { return <main className="mx-auto max-w-3xl p-10"><div className="rounded-3xl border border-slate-200 bg-white p-8 text-center"><p className="text-slate-700">{text}</p>{action && <button className="mt-5 rounded-xl bg-slate-950 px-4 py-2 text-sm font-semibold text-white" onClick={action}>Reintentar</button>}</div></main>; }
